import main from 'main-function';

main(async () => {
  throw new Error('hello, error!');
});
